---
# Install some YUM packages and make sure the system is up to date.
- name: Yum | Update system.
  yum: name=* state=latest

- name: Yum | Install user tools.
  yum: name={{ item }} state=latest
  with_items:
  - vim
  - git
  - curl
  - python-pip
