---
# Verb API Deployment
- name: deploy the latest verb api code.
  hosts: all
  user: portaj
  sudo: yes

  vars_files:
  - secrets.yml

  roles:
    - { role: notify, deploy_status: 'started' }
    - common
    - monitoring
    - verb-api
    - { role: notify, deploy_status: 'finished' }
