---
# Pull jonathanporta/verb-api docker image, start it
- name: Deploy | Pull latest verb-api image from Docker hub
  shell: docker pull jonathanporta/verb-api:latest

- name: Deploy | Ensure data directory exists
  file: path="{{ install_directory }}/data/development" state=directory

- name: Ensure verb-api container is stopped
  docker:
    image: jonathanporta/verb-api
    name: verb_api
    state: absent

- name: Ensure verb-db container is stopped
  docker:
    image: postgres
    name: verb_db
    state: absent

- name: Deploy | Ensure data container is running
  docker:
    image: ubuntu
    name: verb_data
    volumes: "{{ install_directory }}/data:/verbdata"

- name: Deploy | Ensure postgres container is running
  docker:
    image: postgres
    name: verb_db
    env: "PGDATA=/verbdata/development"
    volumes_from: verb_data
    state: running

- name: Ensure verb-api container is running
  docker:
    image: jonathanporta/verb-api
    name: verb_api
    env: "RAILS_ENV=development,FB_APP_ID={{ FB_APP_ID }},FB_APP_SECRET={{ FB_APP_SECRET }},DB_USERNAME={{ DB_USERNAME }},DB_PASSWORD={{ DB_PASSWORD }}"
    ports: "{{ port }}:{{ port }}"
    links: verb_db:db
    state: running
    volumes: "{{ config_directory }}/certs:/home/app/config/certs"
