---
# Pull jonathanporta/verb-api docker image, start it
- name: Deploy | Pull latest verb-api image from Docker hub
  shell: docker pull jonathanporta/verb-api:latest

- name: Deploy | Ensure data directory exists
  file: path="{{ install_directory }}/data/development" state=directory

- name: Deploy | verb_data service file
  template: src=verb_data.service dest=/etc/systemd/system/verb_data.service

- name: Deploy | verb_db service file
  template: src=verb_db.service dest=/etc/systemd/system/verb_db.service

- name: Deploy | verb_api service file
  template: src=verb_api.service dest=/etc/systemd/system/verb_api.service

- name: Deploy | Tell systemd to reload
  command: systemctl daemon-reload

- name: Deploy | verb_data service enable and start
  service: name=verb_data state=restarted

- name: Deploy | verb_db service enable and start
  service: name=verb_db state=restarted

- name: Deploy | verb_api service enable and start
  service: name=verb_api state=restarted
